services:
  web:
    build: 
      context: apps/web
      dockerfile: Dockerfile
    image: undercry927/volcano-web:latest
    ports:
      - "5000:5000"
  
  api:
    build: 
      context: apps/api
      dockerfile: Dockerfile
    image: undercry927/volcano-api:latest
    ports:
      - "3000:3000"

  nginx:
    build: 
      context: apps/nginx
      dockerfile: Dockerfile
    image: undercry927/volcano-nginx:latest
    ports:
      - "80:80"
      - "443:443"

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "54432:5432"