FROM node:20.15-slim as base

RUN apt-get update -y && \
    apt-get install -y openssl

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

FROM base as builder

WORKDIR /app

COPY . .

RUN pnpm install
RUN pnpm run db:generate
RUN pnpm build

FROM base as production

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/prisma ./prisma
COPY .env.production .env

EXPOSE 3000

CMD ["pnpm", "run", "production"]